"""add shared_passwords table and key_version to vault

Revision ID: 49f39526fbb7
Revises: 5c0a72cb43ff
Create Date: 2026-06-06 14:32:29.901746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49f39526fbb7'
down_revision: Union[str, Sequence[str], None] = '5c0a72cb43ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
