"""add key_version to vault

Revision ID: 5c0a72cb43ff
Revises: 655cf6c1aebd
Create Date: 2026-06-04 07:16:59.694556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c0a72cb43ff'
down_revision: Union[str, Sequence[str], None] = '655cf6c1aebd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vault', sa.Column('key_version', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vault', 'key_version')
    # ### end Alembic commands ###
