"""add shared_passwords table

Revision ID: 655cf6c1aebd
Revises: d0ac60103989
Create Date: 2026-06-02 07:05:05.331468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '655cf6c1aebd'
down_revision: Union[str, Sequence[str], None] = 'd0ac60103989'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('unique_owner_shares_unique_passwords_to_unique_users'), 'shared_passwords', type_='unique')
    op.create_unique_constraint('unique_vault_shared_with', 'shared_passwords', ['shared_with', 'vault_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_vault_shared_with', 'shared_passwords', type_='unique')
    op.create_unique_constraint(op.f('unique_owner_shares_unique_passwords_to_unique_users'), 'shared_passwords', ['owner_id', 'shared_with', 'vault_id'])
    # ### end Alembic commands ###
