"""add shared_passwords table

Revision ID: d0ac60103989
Revises: f3edf6f5b556
Create Date: 2026-05-31 13:48:01.986459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0ac60103989'
down_revision: Union[str, Sequence[str], None] = 'f3edf6f5b556'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shared_passwords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vault_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('shared_with', sa.Integer(), nullable=False),
    sa.Column('permission', sa.String(), server_default='view', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shared_with'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vault_id'], ['vault.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'shared_with', 'vault_id', name='unique_owner_shares_unique_passwords_to_unique_users')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shared_passwords')
    # ### end Alembic commands ###
